### ISSUE TITLE
render markdown tables as tables in preview

### ISSUE THREAD

**Issue by the42** [jcs-elpa/impatient-showdown#9]
Currently tables are not rendered in preview but shown verbatim, without using any table html codes. It would be great if showdown mode could render html tables out of markdown table syntax.

**Comment by jcs090218** [comment]
I'll look into it! Thanks!

**Comment by the42** [comment]
referencing #10

**Comment by jcs090218** [comment]
Awesome! Thank you for your contribution! 😁
